---
title: "d3-2 data (top 100 with classes)"
---

//////////////
Redo d3-2 to reconstruct totals without .json values
Add links to sidebar

Trying a new filtering technique.
```{r, eval=FALSE}
library(tidyverse)
new100 <- read_csv(file="top102.csv", col_names = FALSE) %>%
  rename('Title' = 'X1', 'Class' = 'X2')


# However! How will this work if I'm building it to grouped drugs?

#Export 100 as .json
#new100 %>%
#  jsonlite::toJSON() %>%
#  write(file="archive/new100.json")

#new100 %>%
#  jsonlite::toJSON() %>%
#  write(file="docs/dev/new100.json")
```


//////////////////

This continues to use variables set in the workbook.rmd environment.

///////////////////////////////////////////////////////////////

#Shortlist top 100.
```{r}
#Reclassify title, remove whitespace
master$title <- as.character(master$title) %>%
  trimws("both")

#Create database subsetted from master
top100master <- master %>%
  filter(master$title %in% top100$X1)

#Remove imports/ severity / evidence / interactions info.
#Find positions of imports not listed. make vector - remove severity / evidence / interactions info.
for (i in 1:nrow(top100master)){
   arentindex <- which(!top100master[i,]$imports[[1]] %in% top100master$name)
  top100master[i,]$imports[[1]] <- top100master[i,]$imports[[1]][-c(arentindex)]
  top100master[i,]$Severity[[1]] <- top100master[i,]$Severity[[1]][-c(arentindex)]
  top100master[i,]$Evidence[[1]] <- top100master[i,]$Evidence[[1]][-c(arentindex)]
  top100master[i,]$`Interactions Info`[[1]] <- top100master[i,]$`Interactions Info`[[1]][-c(arentindex)]
}

#Introduce severity totals
top100master <- top100master %>%
  mutate(mildtot = str_count(top100master$Severity, "Mild")) %>%
  mutate(modtot = str_count(top100master$Severity, "Moderate")) %>%
  mutate(sevtot = str_count(top100master$Severity, "Severe")) %>%
  mutate(nstot = str_count(top100master$Severity, "NotSet") + 
           str_count(top100master$Severity, "Unknown"))

#Introduce evidence totals
top100master <- top100master %>%
  mutate(studytot = str_count(top100master$Evidence, "Study")) %>%
  mutate(anectot = str_count(top100master$Evidence, "Anecdotal")) %>%
  mutate(theorettot = str_count(top100master$Evidence, "Theoretical")) %>%
  mutate(nsetot = str_count(top100master$Evidence, "NotSet"))
```

#Export 100 data
```{r}
#Copy to 'archive'
top100master %>%
  jsonlite::toJSON() %>%
  write(file="archive/flare100.json")

#Copy to 'docs/dev'
top100master %>%
  jsonlite::toJSON() %>%
  write(file="docs/dev/flare100.json")

#Copy to archive with a timestamp
jsonName100 <- str_c("archive/", str_replace_all(Datestamp, " ", ""), "flare100.json")
master %>%
  jsonlite::toJSON() %>%
  write(file = jsonName100)
```

#100 data with classes
```{r, message=FALSE, warning=FALSE}
#Import original 100 drugs list, with classes
drugclasses <- read_csv("~/Dropbox/D3/top102.csv", col_names = FALSE) %>%
  rename('Title' = 'X1', 'Class' = 'X2')

top100classes <- dataframe %>%
  filter(trimws(as.character(dataframe$Title), "both") %in% drugclasses$Title)

dataframe$Title <- as.character(dataframe$Title) %>%
  trimws("both")

top100drugs <- dplyr::inner_join(drugclasses, dataframe, by = "Title")
top100drugs$importstitle <- top100drugs$Interactions
top100drugs$name <- top100drugs$Title

#Edit out extra drugs 
for (i in 1:nrow(top100drugs)){
   arentindex <- which(!top100drugs[i,]$importstitle[[1]] %in% top100drugs$Title)
  top100drugs[i,]$importstitle[[1]] <- top100drugs[i,]$importstitle[[1]][-c(arentindex)]
  top100drugs[i,]$Interactions[[1]] <- top100drugs[i,]$Interactions[[1]][-c(arentindex)]
  top100drugs[i,]$Severity[[1]] <- top100drugs[i,]$Severity[[1]][-c(arentindex)]
  top100drugs[i,]$Evidence[[1]] <- top100drugs[i,]$Evidence[[1]][-c(arentindex)]
  top100drugs[i,]$`Interactions Info`[[1]] <- top100drugs[i,]$`Interactions Info`[[1]][-c(arentindex)]
}

#Add Severity Totals
top100drugs <- top100drugs %>%
  mutate(mildtot = str_count(top100drugs$Severity, "Mild")) %>%
  mutate(modtot = str_count(top100drugs$Severity, "Moderate")) %>%
  mutate(sevtot = str_count(top100drugs$Severity, "Severe")) %>%
  mutate(nstot = str_count(top100drugs$Severity, "NotSet") + 
           str_count(top100drugs$Severity, "Unknown"))

#Add Evidence Totals
top100drugs <- top100drugs %>%
  mutate(studytot = str_count(top100drugs$Evidence, "Study")) %>%
  mutate(anectot = str_count(top100drugs$Evidence, "Anecdotal")) %>%
  mutate(theorettot = str_count(top100drugs$Evidence, "Theoretical")) %>%
  mutate(nsetot = str_count(top100drugs$Evidence, "NotSet"))

#Relabel 'Title'
top100drugs$Title <- str_c("BNF.", top100drugs$Class, ".", top100drugs$name) %>%
  str_replace_all(pattern=" ", replacement="")

#Relabel 'imports'
node.parent.child <- function(x) {
    example <- top100drugs[x,] %>%
    select('Interactions') %>%
    unlist() %>%
    as.character() 

    if (length(example) > 0) {
    examplelist <- c(1:length(example))
    
    for (i in 1:length(example)){
    examplename <- filter(top100drugs, name == example[i]) %>%
    select(Title)
    examplelist[i] <- examplename[[1]]
    }
    
    top100drugs$Interactions[x][[1]] <- examplelist
    } else {top100drugs$Interactions[x][[1]] <- character(0)}
    
    }
top100drugs$Interactions <- lapply(1:nrow(top100drugs), node.parent.child)

#Tidy up
top100drugs <- top100drugs %>%
  rename('title' = 'name') %>%
  rename('name' = 'Title') %>%
  rename('imports' = 'Interactions')
```

d3-2 data (top 100 with classes)
```{r}
#Export
top100drugs$Stamp <- Timestamp

top100drugs %>%
  select(-c(7:14)) %>%
  jsonlite::toJSON() %>%
  write(file="archive/flareexample.json")

#Copy to 'docs/dev'
top100drugs %>%
  select(-c(7:14)) %>%
  jsonlite::toJSON() %>%
  write(file="docs/dev/flareexample.json")

#Copy to archive with a timestamp
jsonName100classes <- str_c("archive/", str_replace_all(Datestamp, " ", ""), "flareexample.json")
top100drugs %>%
  select(-c(7:14)) %>%
  jsonlite::toJSON() %>%
  write(file = jsonName100classes)
```
