---
title: "Plotting BNF Interactions"
---
```{r, warning=FALSE, message=FALSE}
library(rvest)
library(magrittr)
library(stringr)
library(stringi)
library(tidyverse)
```

#Create the drugs look-up.
```{r}
#Get a list of links to test
drugs_list <- readLines("https://bnf.nice.org.uk/interaction/") %>%
  str_match_all("<a href=\"(.*?)\"><span>(.*?)</span>") %>%
  unlist() %>%
  data.frame()

#Replace odd characters
drugs_list$. <- str_replace(drugs_list$., "&#233;", replacement = "é")

#Create a dataframe from it.
drugs_list <-  drugs_list %>%
  data.frame(cbind(observation = rep(1:(nrow(drugs_list)/3), each=3))) %>%
  data.frame(cbind(class = c("String", "Link", "Title"))) %>%
  rename(value = '.') %>%
  spread(key=class, value=value)

#Remove non-drug links
drugs_list <- drugs_list %>%
  filter(stri_detect_fixed(drugs_list$Link, "title=") == FALSE)

#Remove defunct columns
drugs_list <- drugs_list %>%
    select(-observation) %>%
    select(-String)

#Remove some leftover tags
drugs_list$Title <- str_replace(drugs_list$Title, "<sub>", replacement = "")
drugs_list$Title <- str_replace(drugs_list$Title, "</sub>", replacement = "")

#Add a string column
drugs_list <- cbind(drugs_list, 
                    string = str_replace(drugs_list$Link, ".html", replacement = ""))

#Add CSS tag and URL columns
drugs_list <- cbind(drugs_list, 
                    url = str_c("https://bnf.nice.org.uk/interaction/", 
                                drugs_list$string, ".html"))
drugs_list <- cbind(drugs_list, css_string = str_c("#", drugs_list$string, " .interactant span"))

#Convert to character classes
drugs_list[] <- lapply(drugs_list, as.character)

#Set a timestamp for the data collection
drugs_listDatestamp <- Sys.Date()
```

#Compare to last drugslist
```{r}
example <- read_csv("archive/drugs_list.csv")
newdrugs <- setdiff(trimws(drugs_list$Title, "both"), example$Title)
rm(example)
```

#If newdrugs > 0
# haven't worked out what will happen if drug is removed yet
```{r}
if (length(newdrugs) > 0) {
  newdrugName <- str_c("archive/newdrugs/", drugs_listDatestamp) %>%
  str_replace_all(" ", "") %>%
  str_c("drugchange.csv")
write.csv(newdrugs, newdrugName)
}
rm(newdrugs)
```

#Export Drugs_list
```{r, eval=FALSE}
drugs_listName <- str_c("archive/", drugs_listDatestamp) %>%
  str_replace_all(" ", "") %>%
  str_c("drugs_list.csv")
write.csv(drugs_list, drugs_listName)

#overwrite as the most recent drugs_list 
write.csv(drugs_list, "archive/drugs_list.csv")
```

#Scrape Data
```{r}
#Data
data <- sapply(drugs_list$url, function(x)
               read_html(x) %>%
               list())

#Set a timestamp for the data collection
Timestamp <- Sys.time()
Datestamp <- Sys.Date()
```

#Constructing interactions database from Data
```{r}
##Title
dataframe <- data.frame(Title = drugs_list$Title)

##Interactions
alli <- lapply(data,
                function(url){
                    url %>% 
                    html_nodes(css = ".interactant span") %>%
                    html_text()
                })

#Set ordinal factor for severity
severity <- c("NotSet", "Unknown", "Mild", "Moderate", "Severe")
severity <- factor(severity, levels=c("NotSet", "Unknown", "Mild", "Moderate", "Severe"), ordered=TRUE)

#All Severity
severityi2 <- lapply(1:length(data), function(x) {
sections <- html_nodes(data[[x]], "div.span9.interaction-messages")
lapply(1:length(sections), function(x1, x){
#Returns Max value in multiples.
if (length(sections[[x1]]) > 1) {
  sections[[x1]] %>% 
    html_children() %>% 
    html_attr("class") %>% 
    str_replace_all("interaction-message  ", "") %>% 
    max()
  } else {
  sections[[x1]] %>% 
     html_children() %>% 
     html_attr("class") %>%
     str_replace_all("interaction-message  ", "")
  }
  }
) %>%
unlist()
})

#All Evidence
evidencei2 <- lapply(1:length(data), function(x) {
sections <- html_nodes(data[[x]], "div.span9.interaction-messages")

lapply(1:length(sections), function(x1, x){
#Returns Max value in multiples.
if (length(sections[[x1]] %>% 
    html_nodes("dd~ dd")) > 0) {
  sections[[x1]] %>% 
    html_nodes("dd~ dd") %>%
    html_text() %>%
    min()
  } else {
  as.character("NotSet")
  }
  }
) %>%
unlist()
})

#Combine multiple divs under one interaction
infoi2 <- lapply(1:length(data), function(x) {
sections <- html_nodes(data[[x]], "div.span9.interaction-messages")

lapply(1:length(sections), function(x1, x){
#Returns Max value in multiples.
if (length(sections[[x1]]) > 1) {
  sections[[x1]] %>% 
    html_nodes(css = ".interaction-message div") %>% 
    html_text() %>% 
    str_replace_all("\n", replacement="") %>% 
    str_trim() %>% 
    paste(sep="", collapse="")
  } else {
  sections[[x1]] %>% 
    html_nodes(css = ".interaction-message div") %>% 
    html_text() %>% 
    str_replace_all("\n", replacement="") %>% 
    str_trim()
  }
  }
) %>%
unlist()
})

#Bind columns
dataframe <- cbind(dataframe, 
                           data_frame(alli), 
                           data_frame(severityi2),
                           data_frame(evidencei2),
                           data_frame(infoi2))

#Rename columns
dataframe <-  dataframe %>%
  rename(Interactions = 'alli',
         Severity = 'severityi2', 
         Evidence = 'evidencei2',
         'Interactions Info' = 'infoi2')

##Totals
dataframe$'Interaction Total' <- lapply(1:nrow(dataframe), function(x){
                    unlist(length(alli[[x]]))
                })
dataframe$'Severity Total' <- lapply(1:nrow(dataframe), function(x){
                    unlist(length(dataframe$Severity[[x]]))
                })
dataframe$'Evidence Total' <- lapply(1:nrow(dataframe), function(x){
                    unlist(length(dataframe$Evidence[[x]]))
                })
dataframe$'Interactions Info Total' <- lapply(1:nrow(dataframe), function(x){
                    unlist(length(dataframe$'Interactions Info'[[x]]))
                })
rm(alli)
rm(severityi2)
rm(evidencei2)
rm(infoi2)
```

#Check Data completion.
```{r}
dataframe$'Complete Data' <- lapply(1:nrow(dataframe), function(x){
                    if (dataframe$`Interaction Total`[[x]] == dataframe$`Severity Total`[[x]] &
                        dataframe$`Interaction Total`[[x]] == dataframe$`Interactions Info Total`[[x]]  &
                        dataframe$`Interaction Total`[[x]] == dataframe$`Evidence Total`[[x]])
                    {TRUE} else {FALSE}
})
```

Everything there?
```{r}
sum(unlist(dataframe$'Complete Data')) == nrow(dataframe)
```

Export dataframe
```{r, eval=FALSE}
dataframeName <- str_c("archive/", Datestamp) %>%
str_replace_all(" ", "") %>%
str_c("dataframe.Rda")
save(dataframe, file=dataframeName)
```

Make a databse for JSON Format
```{r}
#Create a new database
master <- dataframe %>%
  select('Title', 'Interactions', 'Severity', 'Evidence', 'Interactions Info') %>%
  rename(name = 'Title',
         imports = 'Interactions')
master$title <- master$name

#Added an unlabled column
master$importstitle <- master$imports

#master
master$name <- as.character(master$name)
master$name <- trimws(master$name, "both")

master$title <- as.character(master$title)
master$title <- trimws(master$title, "both")

##remove odd characters in $name
faultycharacters <- str_detect(master$name, "\\(") | str_detect(master$name, string="\\)") | grepl(pattern = "/", x = master$name) | grepl(pattern = "'", x = master$name) | grepl(pattern = ",", x = master$name)
faultyvalues <- master$name[faultycharacters]
faultyvaluesindex <- which(faultycharacters)

##remove odd characters in $name
for (i in faultyvaluesindex){
 master$name[i] <- master$name[i] %>%
  stri_replace_all_regex(pattern = "/", replacement = " ") %>%
  str_replace_all(pattern = "\\(", replacement = "") %>%
  str_replace_all(pattern = "\\)", replacement = "") %>%
  stri_replace_all_regex(pattern = "'", replacement = "") %>%
  stri_replace_all_regex(pattern = ",", replacement = "")
}

for (i in 1:length(master$imports)){
example <- list()
example[[1]] <- master$imports[i] %>%
  unlist() %>%
  stri_replace_all_regex(pattern = "/", replacement = " ") %>%
  str_replace_all(pattern = "\\(", replacement = "") %>%
  str_replace_all(pattern = "\\)", replacement = "") %>%
  stri_replace_all_regex(pattern = "'", replacement = "") %>%
  stri_replace_all_regex(pattern = ",", replacement = "")
master$imports[i] <- example
}

#Relabel 'name'
master$name <- str_c("BNF.", master$name, ".", master$name) %>%
  str_replace_all(pattern=" ", replacement="")

#Relabel 'interactions'
node.parent.child <- function(x) {
  example <- master[x,] %>%
    select('imports') %>%
    unlist() %>%
    as.character() 
  
  example <- str_c(".", example) %>%
    str_dup(times=2)
  
  example <- str_c("BNF", example) %>%
    str_replace_all(pattern=" ", replacement="")
  return(as.vector(example))
}
master$imports <- lapply(1:nrow(master), node.parent.child)
```

#Add totals
```{r, eval=FALSE}
master <- master %>%
  mutate(mildtot = str_count(master$Severity, "Mild")) %>%
  mutate(modtot = str_count(master$Severity, "Moderate")) %>%
  mutate(sevtot = str_count(master$Severity, "Severe")) %>%
  mutate(nstot = str_count(master$Severity, "NotSet") + 
           str_count(master$Severity, "Unknown"))

master <- master %>%
  mutate(studytot = str_count(master$Evidence, "Study")) %>%
  mutate(anectot = str_count(master$Evidence, "Anecdotal")) %>%
  mutate(theorettot = str_count(master$Evidence, "Theoretical")) %>%
  mutate(nsetot = str_count(master$Evidence, "NotSet"))
```

```{r}
#Export
master$Stamp <- Timestamp

master %>%
  jsonlite::toJSON() %>%
  write(file="archive/flare.json")

jsonName <- str_c("archive/", str_replace_all(Datestamp, " ", ""), "flare.json")
master %>%
  jsonlite::toJSON() %>%
  write(file = jsonName)

master %>%
  jsonlite::toJSON() %>%
  write(file="docs/dev/flare.json")
```
