
```{r}
top102 <- read_csv("~/Dropbox/D3/top102.csv", col_names = FALSE) %>%
  rename('Title' = 'X1')
```

```{r}
dataframe$Title <- as.character(dataframe$Title) %>%
  trimws("both")
top100classes <- dataframe %>%
  filter(dataframe$Title %in% top102$Title)
```

```{r}
top100drugs <- dplyr::inner_join(top102, dataframe, by = "Title")
top100drugs <- top100drugs[,1:6]

top100drugs$importstitle <- top100drugs$Interactions
top100drugs$name <- top100drugs$Title
```

```{r}
for (i in 1:nrow(top100drugs)){
   arentindex <- which(!top100drugs[i,]$importstitle[[1]] %in% top100drugs$Title)
  top100drugs[i,]$importstitle[[1]] <- top100drugs[i,]$importstitle[[1]][-c(arentindex)]
  top100drugs[i,]$Interactions[[1]] <- top100drugs[i,]$Interactions[[1]][-c(arentindex)]
  top100drugs[i,]$Severity[[1]] <- top100drugs[i,]$Severity[[1]][-c(arentindex)]
  top100drugs[i,]$Evidence[[1]] <- top100drugs[i,]$Evidence[[1]][-c(arentindex)]
  top100drugs[i,]$`Interactions Info`[[1]] <- top100drugs[i,]$`Interactions Info`[[1]][-c(arentindex)]
}
```

Now introducing some totals for evidence and severity so I don't have to do it in JS.
```{r}
top100drugs <- top100drugs %>%
  mutate(mildtot = str_count(top100drugs$Severity, "Mild")) %>%
  mutate(modtot = str_count(top100drugs$Severity, "Moderate")) %>%
  mutate(sevtot = str_count(top100drugs$Severity, "Severe")) %>%
  mutate(nstot = str_count(top100drugs$Severity, "NotSet"))

top100drugs <- top100drugs %>%
  mutate(studytot = str_count(top100drugs$Severity, "Study")) %>%
  mutate(anectot = str_count(top100drugs$Severity, "Anecdotal")) %>%
  mutate(theorettot = str_count(top100drugs$Severity, "Theoretical")) %>%
  mutate(nsetot = str_count(top100drugs$Severity, "NotSet"))
```
////////

```{r}
#Relabel 'Title'
top100drugs$Title <- str_c("BNF.", top100drugs$X2, ".", top100drugs$name) %>%
  str_replace_all(pattern=" ", replacement="")

#Relabel 'imports'
node.parent.child <- function(x) {
    example <- top100drugs[x,] %>%
    select('Interactions') %>%
    unlist() %>%
    as.character() 

    if (length(example) > 0) {
    examplelist <- c(1:length(example))
    
    for (i in 1:length(example)){
    examplename <- filter(top100drugs, name == example[i]) %>%
    select(Title)
    examplelist[i] <- examplename[[1]]
    }
    
    top100drugs$Interactions[x][[1]] <- examplelist
    } else {top100drugs$Interactions[x][[1]] <- character(0)}
    
    }
top100drugs$Interactions <- lapply(1:nrow(top100drugs), node.parent.child)
```

//should redo earlier in the process
```{r}
top100drugs <- top100drugs %>%
  rename('title' = 'name') %>%
  rename('name' = 'Title') %>%
  rename('imports' = 'Interactions')
```

```{r}
top100drugs %>%
  jsonlite::toJSON() %>%
  write(file="archive/flareexample.json")
```
