---
title: "R Notebook"
---

```{r, warning=FALSE, message=FALSE}
library(rvest)
library(magrittr)
library(stringr)
library(stringi)
library(tidyverse)
```

```{r}
master2 <- master
master2$interactioninfo <- example_dataframe$`Interactions Info`
master2$title <- example_dataframe$Title %>%
  str_trim()
master2$imports2 <- example_dataframe$Interactions
```

```{r, message=FALSE}
top102 <- read_csv("~/Dropbox/D3/top102.csv", col_names = FALSE) %>%
  dplyr::rename(title = X1) %>%
  dplyr::rename(Class = X2)
top102 <- master2 %>%
  filter(title %in% top102$title) %>%
  left_join(top102, by = "title")
```

Rename the name
```{r}
renamename <- function(x) {
  example <- top102[x,] %>%
    select('title') %>%
    unlist() %>%
    as.character()
  example <- str_c("BNF.", top102[x,]$Class, ".", example) %>%
    str_replace_all(pattern=" ", replacement="")
  return(as.vector(example))
}
top102$name <- lapply(1:nrow(top102), renamename)
```

Remove extra interactions
```{r}
removenames <- function(x) {
  top102$imports2[[x]] <- top102$imports2[[x]][top102$imports2[[x]] %in% top102$title == TRUE]
}
top102$imports <- lapply(1:nrow(top102), removenames)
top102 <- top102[-c(4)]
```

remove duplicates/ blank no interactions
```{r}
top102 <- top102[-c(9,14,33,43,58), ]
top102[c(22,48,55,57,64),]$imports <- ""
```

Renaming the interactions
for each character, match to title, then name on same row
```{r}
changenames <- function(x) {
top102$imports[[x]] <- unlist(lapply(1:length(top102$imports[[x]]), function(z) {
  filter(top102, title == top102$imports[[x]][z])$name
  }))
return(as.vector(top102$imports[[x]]))
}

top102$imports[[1]] <- changenames(1)
top102$imports[[2]] <- changenames(2)
top102$imports[[3]] <- changenames(3)
top102$imports[[4]] <- changenames(4)
top102$imports[[5]] <- changenames(5)
top102$imports[[6]] <- changenames(6)
top102$imports[[7]] <- changenames(7)
top102$imports[[8]] <- changenames(8)
top102$imports[[9]] <- changenames(9)
top102$imports[[10]] <- changenames(10)
top102$imports[[11]] <- changenames(11)
top102$imports[[12]] <- changenames(12)
top102$imports[[13]] <- changenames(13)
top102$imports[[14]] <- changenames(14)
top102$imports[[15]] <- changenames(15)
top102$imports[[16]] <- changenames(16)
top102$imports[[17]] <- changenames(17)
top102$imports[[18]] <- changenames(18)
top102$imports[[19]] <- changenames(19)
top102$imports[[20]] <- changenames(20)
top102$imports[[21]] <- changenames(21)
#top102$imports[[22]] <- changenames(22)
top102$imports[[23]] <- changenames(23)
top102$imports[[24]] <- changenames(24)
top102$imports[[25]] <- changenames(25)
top102$imports[[26]] <- changenames(26)
top102$imports[[27]] <- changenames(27)
top102$imports[[28]] <- changenames(28)
top102$imports[[29]] <- changenames(29)
top102$imports[[30]] <- changenames(30)
top102$imports[[31]] <- changenames(31)
top102$imports[[32]] <- changenames(32)
top102$imports[[33]] <- changenames(33)
top102$imports[[34]] <- changenames(34)
top102$imports[[35]] <- changenames(35)
top102$imports[[36]] <- changenames(36)
top102$imports[[37]] <- changenames(37)
top102$imports[[38]] <- changenames(38)
top102$imports[[39]] <- changenames(39)
top102$imports[[40]] <- changenames(40)
top102$imports[[41]] <- changenames(41)
top102$imports[[42]] <- changenames(42)
top102$imports[[43]] <- changenames(43)
top102$imports[[44]] <- changenames(44)
top102$imports[[45]] <- changenames(45)
top102$imports[[46]] <- changenames(46)
top102$imports[[47]] <- changenames(47)
#top102$imports[[48]] <- changenames(48)
top102$imports[[49]] <- changenames(49)
top102$imports[[50]] <- changenames(50)
top102$imports[[51]] <- changenames(51)
top102$imports[[52]] <- changenames(52)
top102$imports[[53]] <- changenames(53)
top102$imports[[54]] <- changenames(54)
#top102$imports[[55]] <- changenames(55)
top102$imports[[56]] <- changenames(56)
#top102$imports[[57]] <- changenames(57)
top102$imports[[58]] <- changenames(58)
top102$imports[[59]] <- changenames(59)
top102$imports[[60]] <- changenames(60)
top102$imports[[61]] <- changenames(61)
top102$imports[[62]] <- changenames(62)
top102$imports[[63]] <- changenames(63)
#top102$imports[[64]] <- changenames(64)
top102$imports[[65]] <- changenames(65)
top102$imports[[66]] <- changenames(66)
top102$imports[[67]] <- changenames(67)
top102$imports[[68]] <- changenames(68)
top102$imports[[69]] <- changenames(69)
top102$imports[[70]] <- changenames(70)
top102$imports[[71]] <- changenames(71)
top102$imports[[72]] <- changenames(72)
top102$imports[[73]] <- changenames(73)
top102$imports[[74]] <- changenames(74)
top102$imports[[75]] <- changenames(75)
top102$imports[[76]] <- changenames(76)
top102$imports[[77]] <- changenames(77)
top102$imports[[78]] <- changenames(78)
top102$imports[[79]] <- changenames(79)
top102$imports[[80]] <- changenames(80)
top102$imports[[81]] <- changenames(81)
top102$imports[[82]] <- changenames(82)
top102$imports[[83]] <- changenames(83)
top102$imports[[84]] <- changenames(84)
top102$imports[[85]] <- changenames(85)
top102$imports[[86]] <- changenames(86)
top102$imports[[87]] <- changenames(87)
top102$imports[[88]] <- changenames(88)
top102$imports[[89]] <- changenames(89)
```

Add bnf.classes.classes
```{r}
extra <- as_data_frame(str_c("BNF.", unique(top102$'Class'), ".", unique(top102$'Class'))) %>%
  rename(name = value)
extra$imports <- ""
extra$title <- ""
extra$interactioninfo <- ""
extra$Class <- ""

top103 <- rbind(top102, extra)
```

```{r, eval=FALSE}
top103[1:2] %>%
  jsonlite::toJSON() %>%
  write(file="docs/flare5.json")
```

```{r, eval=FALSE}
top102[1:2] %>%
  jsonlite::toJSON() %>%
  write(file="docs/flare4.json")
```